{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Transform",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Cone.ByPointsRadius@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,double",
      "Id": "9353c4dfe5c94c3b89718f7d9b2123ba",
      "Inputs": [
        {
          "Id": "0da31304e3c743d9b2389d27d128f7e6",
          "Name": "startPoint",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "78e6088558c14cd0b6cc6fa794380d52",
          "Name": "endPoint",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 1)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1758f7227be74946a717de527d5b1617",
          "Name": "startRadius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9f345c3d645d460fb69b21dd4340f58d",
          "Name": "Cone",
          "Description": "Cone",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Cone with given base radius at start Point, extending to a apex at end Point.\n\nCone.ByPointsRadius (startPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), endPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 1), startRadius: double = 1): Cone"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "fb784abe345a49ce9476f22cbf49e7a9",
      "Inputs": [
        {
          "Id": "30d4542471c6474d9245a23fbcfc2842",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "af824408caf54142864b46d1b34bb833",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fb057f54ec89417ba48c226a59479176",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6ee3e45b72304345b115fe1c0ca29f95",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "5;\n2;\n8;",
      "Id": "47226805f4414bd689711e386a9009d1",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "fbd6595286e34df392f719480da51973",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8881881e59314e5cae300fc6c9681c6b",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e526992d461349b0a1199a50e2fd1851",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.CoordinateSystem.ByPlane@Autodesk.DesignScript.Geometry.Plane",
      "Id": "9eb873babc494c5ba961b34f1dc934bf",
      "Inputs": [
        {
          "Id": "61503439af274c92bcd40ec335da908c",
          "Name": "plane",
          "Description": "Plane\nDefault value : Autodesk.DesignScript.Geometry.Plane.XY() (disabled)",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f64656e09a8e47c9b79a242a503cd372",
          "Name": "CoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a CoordinateSystem with origin equal to input Plane origin, and X and Y axes lying in the Plane, aligned with Plane X and Y axes.\n\nCoordinateSystem.ByPlane (plane: Plane = Autodesk.DesignScript.Geometry.Plane.XY()): CoordinateSystem"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "af36d39a902b41c5adef72edc68ceae5",
      "Inputs": [
        {
          "Id": "38de27de02fb4846b6b666b5fb0b14cd",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3973fedee33841fbae0557c2b6fafc7f",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5400538aa3364de3a20e0e41f473a1fb",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c5f0144c05474846882a7ea98e6bb5a0",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "8;\n2;\n5;",
      "Id": "3273b2aa4cfd4c3c91550de1891faeaa",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "82c53b780c134f71890da773107e507f",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bca7607419ca4575b61b2ba5a01df70e",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "85521552809c4495973561883690bed5",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Plane.YZ",
      "Id": "d2270a6fafc14f7da9781ece49d76b19",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a229b9e581f44010870b12245e41efc7",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a plane in the world YZ\n\nPlane.YZ ( ): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.Transform@Autodesk.DesignScript.Geometry.CoordinateSystem,Autodesk.DesignScript.Geometry.CoordinateSystem",
      "Id": "33242122c7d240208895dfe38097a6d0",
      "Inputs": [
        {
          "Id": "fab690554dc74d0ebb76f3cfc90cca5a",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b651e7f2aad34427856ead8c7e3fbe65",
          "Name": "fromCoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "13c51adad6b445c5aff3f5dfd6d08a7c",
          "Name": "contextCoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c8fa3347f5b44406b50eab955ab56e86",
          "Name": "Geometry",
          "Description": "Transformed Geometry.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Transforms this geometry from source CoordinateSystem to a new context CoordinateSystem.\n\nGeometry.Transform (fromCoordinateSystem: CoordinateSystem, contextCoordinateSystem: CoordinateSystem): Geometry"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.CoordinateSystem.ByPlane@Autodesk.DesignScript.Geometry.Plane",
      "Id": "89989b49a30642ee8ff8bd10129f876b",
      "Inputs": [
        {
          "Id": "8073de5c433245b49fd840c1f2247051",
          "Name": "plane",
          "Description": "Plane\nDefault value : Autodesk.DesignScript.Geometry.Plane.XY() (disabled)",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4dd9e3698f154abfa3c2c60604fbddac",
          "Name": "CoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a CoordinateSystem with origin equal to input Plane origin, and X and Y axes lying in the Plane, aligned with Plane X and Y axes.\n\nCoordinateSystem.ByPlane (plane: Plane = Autodesk.DesignScript.Geometry.Plane.XY()): CoordinateSystem"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Plane.XY",
      "Id": "ac0eaeae18a0429f8330563600379b70",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "757db0ee17e647d8a3c055971b93c064",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a plane in the world XY\n\nPlane.XY ( ): Plane"
    }
  ],
  "Connectors": [
    {
      "Start": "9f345c3d645d460fb69b21dd4340f58d",
      "End": "fab690554dc74d0ebb76f3cfc90cca5a",
      "Id": "65af51927188457fb5cc9697c36e5404"
    },
    {
      "Start": "6ee3e45b72304345b115fe1c0ca29f95",
      "End": "78e6088558c14cd0b6cc6fa794380d52",
      "Id": "d7597fb53575448ab3281dcb32da985b"
    },
    {
      "Start": "fbd6595286e34df392f719480da51973",
      "End": "30d4542471c6474d9245a23fbcfc2842",
      "Id": "f6726aca77c2432789ef266e516dd2ca"
    },
    {
      "Start": "fbd6595286e34df392f719480da51973",
      "End": "1758f7227be74946a717de527d5b1617",
      "Id": "26f6e1f957384c61b8aa4fa74fdf8903"
    },
    {
      "Start": "8881881e59314e5cae300fc6c9681c6b",
      "End": "af824408caf54142864b46d1b34bb833",
      "Id": "cb30c5384aeb4328b77efe3dba146e75"
    },
    {
      "Start": "e526992d461349b0a1199a50e2fd1851",
      "End": "fb057f54ec89417ba48c226a59479176",
      "Id": "9919a09426624600a85f65665d9054d5"
    },
    {
      "Start": "f64656e09a8e47c9b79a242a503cd372",
      "End": "b651e7f2aad34427856ead8c7e3fbe65",
      "Id": "e0992f43d004423685ce0fd2bb4ff8da"
    },
    {
      "Start": "c5f0144c05474846882a7ea98e6bb5a0",
      "End": "0da31304e3c743d9b2389d27d128f7e6",
      "Id": "1943819f12f04e2492da65bdc21b8a17"
    },
    {
      "Start": "82c53b780c134f71890da773107e507f",
      "End": "38de27de02fb4846b6b666b5fb0b14cd",
      "Id": "7adf2547763b4518ad4d1e94facca495"
    },
    {
      "Start": "bca7607419ca4575b61b2ba5a01df70e",
      "End": "3973fedee33841fbae0557c2b6fafc7f",
      "Id": "4cf6966175564bf2817c0ecf1f3d7ce6"
    },
    {
      "Start": "85521552809c4495973561883690bed5",
      "End": "5400538aa3364de3a20e0e41f473a1fb",
      "Id": "216230f2b151418f94744bbca247e241"
    },
    {
      "Start": "a229b9e581f44010870b12245e41efc7",
      "End": "61503439af274c92bcd40ec335da908c",
      "Id": "9485a0f3e7c14058b107c2a792a09b96"
    },
    {
      "Start": "4dd9e3698f154abfa3c2c60604fbddac",
      "End": "13c51adad6b445c5aff3f5dfd6d08a7c",
      "Id": "c276544a5b9a4c659a526e9ce90e8856"
    },
    {
      "Start": "757db0ee17e647d8a3c055971b93c064",
      "End": "8073de5c433245b49fd840c1f2247051",
      "Id": "26af66b960344246b67c68c92c5f8a45"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.1.5055",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -14.45981502532959,
      "EyeY": 8.7294845581054687,
      "EyeZ": 14.723348617553711,
      "LookX": 18.132101058959961,
      "LookY": -3.0836248397827148,
      "LookZ": -18.012638092041016,
      "UpX": -0.0679967999458313,
      "UpY": 0.9953961968421936,
      "UpZ": 0.067548803985118866
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Cone.ByPointsRadius",
        "Id": "9353c4dfe5c94c3b89718f7d9b2123ba",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 854.69401888585844,
        "Y": 299.18303489483355
      },
      {
        "ShowGeometry": false,
        "Name": "Point.ByCoordinates",
        "Id": "fb784abe345a49ce9476f22cbf49e7a9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 596.69401888585844,
        "Y": 346.18303489483355
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "47226805f4414bd689711e386a9009d1",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 417.69401888585844,
        "Y": 357.10970156150017
      },
      {
        "ShowGeometry": true,
        "Name": "CoordinateSystem.ByPlane",
        "Id": "9eb873babc494c5ba961b34f1dc934bf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 854.69401888585844,
        "Y": 459.18303489483355
      },
      {
        "ShowGeometry": false,
        "Name": "Point.ByCoordinates",
        "Id": "af36d39a902b41c5adef72edc68ceae5",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 596.69401888585844,
        "Y": 185.18303489483355
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "3273b2aa4cfd4c3c91550de1891faeaa",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 417.69401888585844,
        "Y": 197.82303489483351
      },
      {
        "ShowGeometry": true,
        "Name": "Plane.YZ",
        "Id": "d2270a6fafc14f7da9781ece49d76b19",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 596.69401888585844,
        "Y": 506.18303489483355
      },
      {
        "ShowGeometry": true,
        "Name": "Geometry.Transform",
        "Id": "33242122c7d240208895dfe38097a6d0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1219.6150806161781,
        "Y": 416.18303489483355
      },
      {
        "ShowGeometry": true,
        "Name": "CoordinateSystem.ByPlane",
        "Id": "89989b49a30642ee8ff8bd10129f876b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 854.69401888585844,
        "Y": 568.18303489483355
      },
      {
        "ShowGeometry": true,
        "Name": "Plane.XY",
        "Id": "ac0eaeae18a0429f8330563600379b70",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 596.69401888585844,
        "Y": 614.18303489483355
      }
    ],
    "Annotations": [],
    "X": -368.290522442687,
    "Y": -178.880502361945,
    "Zoom": 1.08570356044719
  }
}