<Workspace Version="1.3.0.875" X="-11841.4249342032" Y="-1526.66098577747" zoom="1.77410468743511" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection guid="f466a42b-b2ad-427a-9fca-4b50f482ff23" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="6854.41957454209" y="989.343306621704" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="17836a3c-e764-47fa-a2e0-08216444f621-00078ef8" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="08c17af7-b90a-47b9-a086-04887ce0a411" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Floor.Points" x="7094.63112702969" y="989.294430081959" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Floor.Points">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f466a42b-b2ad-427a-9fca-4b50f482ff23" start_index="0" end="08c17af7-b90a-47b9-a086-04887ce0a411" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>