{
  "Uuid": "803fb2f9-4884-42de-915d-c7831d5e05fe",
  "IsCustomNode": false,
  "Description": null,
  "Name": "AddPoint",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "9e597f98-694d-4ada-b8ef-0e7459e0b930-0002640e"
      ],
      "Id": "aba9eafcae264bdbb700108f6ad71337",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "4f6ee5436064402cbc41e2c09c626af4",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Floor.AddPoint@Autodesk.DesignScript.Geometry.Point",
      "Id": "b939dc74219d48b18e4394dcd6c2e2c8",
      "Inputs": [
        {
          "Id": "c745c72df205494faf84b66cc297b5cc",
          "Name": "floor",
          "Description": "Revit.Elements.Floor",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5dc254652a1042528d49dd41d5ba775a",
          "Name": "point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "660ece2861e54630961ae3ec7dea97d3",
          "Name": "Floor",
          "Description": "Floor",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Add Point to Slab Shape\n\nFloor.AddPoint (point: Point): Floor"
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSPointOnElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "9e597f98-694d-4ada-b8ef-0e7459e0b930-0002640e:1:SURFACE"
      ],
      "Id": "b513108ecc4548e3a21f9bc7bcd6fa58",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "e950b00b58df4941ab1b314edf2cb9ee",
          "Name": "Point",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    }
  ],
  "Connectors": [
    {
      "Start": "4f6ee5436064402cbc41e2c09c626af4",
      "End": "c745c72df205494faf84b66cc297b5cc",
      "Id": "3869ab57115d4a19ba15610ca55a439c"
    },
    {
      "Start": "e950b00b58df4941ab1b314edf2cb9ee",
      "End": "5dc254652a1042528d49dd41d5ba775a",
      "Id": "3eaffe7ceb574a2b8918390c0846fc39"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.1.0.5357",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Select Model Element",
        "Id": "aba9eafcae264bdbb700108f6ad71337",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 107.0,
        "Y": 77.0
      },
      {
        "ShowGeometry": true,
        "Name": "Floor.AddPoint",
        "Id": "b939dc74219d48b18e4394dcd6c2e2c8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 385.0,
        "Y": 150.0
      },
      {
        "ShowGeometry": true,
        "Name": "Select Point on Face",
        "Id": "b513108ecc4548e3a21f9bc7bcd6fa58",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 84.0,
        "Y": 241.0
      }
    ],
    "Annotations": [],
    "X": 0.0,
    "Y": 0.0,
    "Zoom": 1.0
  }
}